#!/usr/bin/env python3
"""Public, self-contained CHL2 H/R/P factor-compatibility audit.

This audit evaluates the complete conditional 2^3 design generated by three
multiplicative factors on one common support:

    H(g2)       = S_Y({0,g2})
    R(g2|g1)    = S_Y({0,g1,g1+g2}) / S_Y({0,g1})
    P(g1,g2)    = exp[-Omega_Y^path(g1,g2;x)]

The eight vertices are:

    H R P   model
    0 0 0   ROW_MASK_ETA
    1 0 0   H2_COND_ETA
    0 1 0   CHL1
    0 0 1   PATH_ONLY_ETA
    1 1 0   CG_MARKOV_ETA
    1 0 1   CG_PATH_ETA
    0 1 1   CHL2
    1 1 1   CG_MARKOV_PATH_ETA

Every vertex uses:

* the same parent-wide conditional support by previous gap g1;
* the same triple-admissibility mask;
* the same empirical state masses P_emp(g1);
* the same terminal mean-g2 target, with a model-specific eta chosen only to
  satisfy that common target.

The script has no dependency on ``chl_lab``.  It consumes parent-wide DS1 block
files plus the path-exclusion cache generated by
``paper_audits/chl2_consecutive_exclusion_audit.py`` and writes compact CSV/JSON
outputs under the requested output directory.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import subprocess
import sys
from concurrent.futures import ProcessPoolExecutor, as_completed
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import numpy as np
import pandas as pd

# Allow execution as a file from a fresh checkout.
_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from chl_kernel.telemetry import telemetry_start, write_telemetry


# ---------------------------------------------------------------------------
# Public design contract
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ModelSpec:
    name: str
    H: int
    R: int
    P: int
    formula: str

    @property
    def signature(self) -> tuple[int, int, int]:
        return (int(self.H), int(self.R), int(self.P))


MODEL_SPECS: tuple[ModelSpec, ...] = (
    ModelSpec("ROW_MASK_ETA", 0, 0, 0, "1_adm * exp(eta*g2)"),
    ModelSpec("H2_COND_ETA", 1, 0, 0, "1_adm * S2(g2) * exp(eta*g2)"),
    ModelSpec("CHL1", 0, 1, 0, "1_adm * R(g2|g1) * exp(eta*g2)"),
    ModelSpec("PATH_ONLY_ETA", 0, 0, 1, "1_adm * P_path(g1,g2) * exp(eta*g2)"),
    ModelSpec("CG_MARKOV_ETA", 1, 1, 0, "1_adm * S2(g2) * R(g2|g1) * exp(eta*g2)"),
    ModelSpec("CG_PATH_ETA", 1, 0, 1, "1_adm * S2(g2) * P_path(g1,g2) * exp(eta*g2)"),
    ModelSpec("CHL2", 0, 1, 1, "1_adm * R(g2|g1) * P_path(g1,g2) * exp(eta*g2)"),
    ModelSpec(
        "CG_MARKOV_PATH_ETA",
        1,
        1,
        1,
        "1_adm * S2(g2) * R(g2|g1) * P_path(g1,g2) * exp(eta*g2)",
    ),
)

MODEL_BY_SIGNATURE = {spec.signature: spec for spec in MODEL_SPECS}
MODEL_BY_NAME = {spec.name: spec for spec in MODEL_SPECS}

if len(MODEL_BY_SIGNATURE) != 8 or len(MODEL_BY_NAME) != 8:  # pragma: no cover
    raise RuntimeError("H/R/P model catalogue must contain exactly eight unique vertices")


FILTERS = {
    "ALL": lambda m: np.ones_like(m, dtype=bool),
    "LOW_ONLY_LE58": lambda m: m <= 58,
    "MID_59_120": lambda m: (m >= 59) & (m <= 120),
    "MID_121_240": lambda m: (m >= 121) & (m <= 240),
    "MID_121_400": lambda m: (m >= 121) & (m <= 400),
    "NO_58": lambda m: m > 58,
    "NO_120": lambda m: m > 120,
    "NO_240": lambda m: m > 240,
}

FILTER_TO_STRATUM = {
    "ALL": "S_all",
    "LOW_ONLY_LE58": "S_dense",
    "MID_59_120": "S_trans",
    "MID_121_240": "S_121_240",
    "MID_121_400": "S_121_400",
    "NO_58": "S_gt_58",
    "NO_120": "S_gt_120",
    "NO_240": "S_gt_240",
}

FACTOR_NAMES = ("H", "R", "P")
FACTORIAL_EFFECTS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("H", ("H",)),
    ("R", ("R",)),
    ("P", ("P",)),
    ("H:R", ("H", "R")),
    ("H:P", ("H", "P")),
    ("R:P", ("R", "P")),
    ("H:R:P", ("H", "R", "P")),
)

MODEL_METRIC_COLUMNS = [
    "block",
    "filter",
    "stratum",
    "model",
    "H",
    "R",
    "P",
    "formula",
    "support_semantics",
    "support_sha256",
    "support_rows",
    "observed_rows",
    "g1_states",
    "n_events",
    "eta",
    "target_mean_g2",
    "mean_g2_model",
    "anchor_abs_error",
    "loglik_sum",
    "loglik_per_event",
    "cross_entropy",
    "empirical_cond_entropy",
    "conditional_kl",
]

MISSING_CELL_COLUMNS = ["block", "filter", "stratum", "model", "reason"]


# ---------------------------------------------------------------------------
# Small utilities
# ---------------------------------------------------------------------------


def parse_block_spec(text: str | None, default: Sequence[int]) -> list[int]:
    if not text:
        return sorted(dict.fromkeys(int(x) for x in default))
    out: list[int] = []
    for part in str(text).split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            a, b = part.split("-", 1)
            out.extend(range(int(a), int(b) + 1))
        else:
            out.append(int(part))
    return sorted(dict.fromkeys(out))


def parse_csv_list(text: str) -> list[str]:
    return list(dict.fromkeys(part.strip() for part in str(text).split(",") if part.strip()))


def primes_upto(n: int) -> list[int]:
    n = int(n)
    if n < 2:
        return []
    sieve = bytearray(b"\x01") * (n + 1)
    sieve[0:2] = b"\x00\x00"
    for p in range(2, int(n**0.5) + 1):
        if sieve[p]:
            start = p * p
            sieve[start : n + 1 : p] = b"\x00" * (((n - start) // p) + 1)
    return [i for i in range(2, n + 1) if sieve[i]]


def logsumexp(values: np.ndarray) -> float:
    a = np.asarray(values, dtype=np.float64)
    if a.size == 0:
        return -math.inf
    m = float(np.max(a))
    if not math.isfinite(m):
        return -math.inf
    return float(m + math.log(float(np.exp(a - m).sum())))


def safe_to_markdown(df: pd.DataFrame, *, index: bool = False) -> str:
    try:
        return df.to_markdown(index=index)
    except Exception:
        return "```\n" + df.to_string(index=index) + "\n```"


def load_json(path: str | Path) -> dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def resolve_block_files(
    config: Mapping[str, Any],
    root: str | Path,
    blocks: Sequence[int],
) -> list[tuple[int, Path]]:
    rootp = Path(root)
    input_dir = rootp / str(config.get("input_dir", ""))
    blocks_dir = input_dir / str(config.get("blocks_dir", "blocks"))
    pattern = str(
        config.get("block_glob")
        or config.get("block_pattern")
        or "parent_wide_B{block:02d}.csv.gz"
    )
    resolved: list[tuple[int, Path]] = []
    for block in blocks:
        candidates: list[Path] = []
        try:
            candidates.append(blocks_dir / pattern.format(block=int(block)))
        except Exception:
            pass
        candidates.extend(
            [
                blocks_dir / f"parent_wide_B{int(block):02d}.csv.gz",
                blocks_dir / f"v46t12_ds_pilot_parent_wide_B{int(block):02d}.csv.gz",
                input_dir / f"parent_wide_B{int(block):02d}.csv.gz",
            ]
        )
        seen: set[str] = set()
        unique_candidates: list[Path] = []
        for candidate in candidates:
            key = str(candidate)
            if key not in seen:
                unique_candidates.append(candidate)
                seen.add(key)
        candidates = unique_candidates
        found = next((p for p in candidates if p.is_file()), None)
        if found is None:
            tried = "\n  ".join(str(p) for p in candidates)
            raise FileNotFoundError(
                f"Could not resolve parent-wide file for block B{int(block):02d}. Tried:\n  {tried}"
            )
        resolved.append((int(block), found))
    return resolved


def support_sha256(df: pd.DataFrame) -> str:
    keys = (
        df[["g1", "g2"]]
        .drop_duplicates()
        .sort_values(["g1", "g2"], kind="mergesort")
        .itertuples(index=False, name=None)
    )
    digest = hashlib.sha256()
    for g1, g2 in keys:
        digest.update(f"{int(g1)},{int(g2)}\n".encode("ascii"))
    return digest.hexdigest()


def sha256_file(path: str | Path, chunk_size: int = 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(int(chunk_size)), b""):
            digest.update(chunk)
    return digest.hexdigest()


def file_provenance(path: str | Path, *, hash_content: bool) -> dict[str, Any]:
    p = Path(path)
    record: dict[str, Any] = {"path": str(p), "exists": bool(p.is_file())}
    if not p.is_file():
        return record
    stat = p.stat()
    record.update(
        {
            "size_bytes": int(stat.st_size),
            "mtime_ns": int(stat.st_mtime_ns),
            "sha256": sha256_file(p) if hash_content else None,
        }
    )
    return record


def git_provenance(repo_root: str | Path) -> dict[str, Any]:
    root = Path(repo_root)

    def run_git(*args: str) -> str | None:
        try:
            proc = subprocess.run(
                ["git", "-C", str(root), *args],
                check=False,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
            )
        except OSError:
            return None
        if proc.returncode != 0:
            return None
        return proc.stdout.strip()

    commit = run_git("rev-parse", "HEAD")
    branch = run_git("rev-parse", "--abbrev-ref", "HEAD")
    describe = run_git("describe", "--tags", "--always", "--dirty")
    status = run_git("status", "--porcelain", "--untracked-files=no")
    tracked_changes = None if status is None else ([x for x in status.splitlines() if x] if status else [])
    return {
        "repo_root": str(root),
        "available": commit is not None,
        "commit": commit,
        "branch": branch,
        "describe": describe,
        "tracked_worktree_clean": None if tracked_changes is None else not bool(tracked_changes),
        "tracked_changes": tracked_changes,
    }


def build_provenance(
    *,
    repo_root: str | Path,
    input_paths: Mapping[str, str | Path | None],
    hash_inputs: bool,
) -> dict[str, Any]:
    inputs = {
        str(label): file_provenance(path, hash_content=bool(hash_inputs))
        for label, path in sorted(input_paths.items())
        if path not in (None, "")
    }
    return {
        "schema": "chl-release-provenance@1",
        "script": file_provenance(Path(__file__).resolve(), hash_content=True),
        "git": git_provenance(repo_root),
        "input_hashes_enabled": bool(hash_inputs),
        "inputs": inputs,
    }


# ---------------------------------------------------------------------------
# Arithmetic factors
# ---------------------------------------------------------------------------


def singular_logs_for_pairs(
    g1: np.ndarray,
    g2: np.ndarray,
    primes: Sequence[int],
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Return log S2(g1), log S3(g1,g2), log R, admissible mask."""
    g1 = np.asarray(g1, dtype=np.int64)
    g2 = np.asarray(g2, dtype=np.int64)
    total = g1 + g2
    n = len(g1)
    log_s2 = np.zeros(n, dtype=np.float64)
    log_s3 = np.zeros(n, dtype=np.float64)
    admissible = np.ones(n, dtype=bool)

    for p in primes:
        pf = float(p)
        g1m = g1 % p
        tm = total % p
        nu2 = np.where(g1m == 0, 1.0, 2.0)
        nu3 = np.ones(n, dtype=np.float64)
        nu3 += g1m != 0
        nu3 += (tm != 0) & (tm != g1m)
        f2 = (1.0 - nu2 / pf) / ((1.0 - 1.0 / pf) ** 2)
        f3 = (1.0 - nu3 / pf) / ((1.0 - 1.0 / pf) ** 3)
        valid = f3 > 0.0
        admissible &= valid
        with np.errstate(divide="ignore", invalid="ignore"):
            log_s2 += np.where(f2 > 0.0, np.log(f2), -np.inf)
            log_s3 += np.where(valid, np.log(f3), -np.inf)

    log_ratio = log_s3 - log_s2
    log_ratio[~admissible] = -np.inf
    return log_s2, log_s3, log_ratio, admissible


def singular_log_s2_gap(g_values: np.ndarray, primes: Sequence[int]) -> tuple[np.ndarray, np.ndarray]:
    g = np.asarray(g_values, dtype=np.int64)
    log_s2 = np.zeros(len(g), dtype=np.float64)
    admissible = np.ones(len(g), dtype=bool)
    for p in primes:
        pf = float(p)
        gm = g % p
        nu2 = np.where(gm == 0, 1.0, 2.0)
        f2 = (1.0 - nu2 / pf) / ((1.0 - 1.0 / pf) ** 2)
        valid = f2 > 0.0
        admissible &= valid
        with np.errstate(divide="ignore", invalid="ignore"):
            log_s2 += np.where(valid, np.log(f2), -np.inf)
    log_s2[~admissible] = -np.inf
    return log_s2, admissible


def load_path_cache(path: str | Path) -> pd.DataFrame:
    p = Path(path)
    if not p.is_file():
        raise FileNotFoundError(p)
    df = pd.read_csv(p)
    required = {"g1", "g2"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Path cache {p} missing required columns {sorted(missing)}")

    out = df[["g1", "g2"]].copy()
    if "logE_path_exclusion" in df.columns:
        out["_log_P"] = pd.to_numeric(df["logE_path_exclusion"], errors="coerce")
    elif "omega_path_exclusion" in df.columns:
        out["_log_P"] = -pd.to_numeric(df["omega_path_exclusion"], errors="coerce")
    elif "omega_path" in df.columns:
        out["_log_P"] = -pd.to_numeric(df["omega_path"], errors="coerce")
    else:
        raise ValueError(
            f"Path cache {p} needs logE_path_exclusion, omega_path_exclusion, or omega_path"
        )

    out["g1"] = pd.to_numeric(out["g1"], errors="raise").astype(np.int64)
    out["g2"] = pd.to_numeric(out["g2"], errors="raise").astype(np.int64)
    if out["_log_P"].isna().any():
        raise ValueError(f"Path cache {p} contains non-numeric path values")

    duplicated = out.duplicated(["g1", "g2"], keep=False)
    if duplicated.any():
        checks = out.loc[duplicated].groupby(["g1", "g2"])["_log_P"].agg(["min", "max"])
        conflicting = checks[(checks["max"] - checks["min"]).abs() > 1e-14]
        if not conflicting.empty:
            raise ValueError(
                f"Path cache {p} contains conflicting duplicate keys: "
                f"{conflicting.head().reset_index().to_dict('records')}"
            )
        out = out.drop_duplicates(["g1", "g2"], keep="first")
    return out.reset_index(drop=True)


# ---------------------------------------------------------------------------
# Common support and terminal anchoring
# ---------------------------------------------------------------------------


def weighted_empirical_cond_entropy(df: pd.DataFrame) -> float:
    obs = df[df["H"] > 0]
    total = float(obs["H"].sum())
    if total <= 0:
        return math.nan
    result = 0.0
    for _, group in obs.groupby("g1", sort=False):
        counts = group["H"].to_numpy(dtype=np.float64)
        state_total = float(counts.sum())
        if state_total <= 0:
            continue
        probs = counts / state_total
        result += (state_total / total) * float(-np.sum(probs * np.log(probs)))
    return float(result)


def conditional_mean_at_eta(
    df: pd.DataFrame,
    log_base: np.ndarray,
    eta: float,
) -> float:
    g1 = df["g1"].to_numpy(dtype=np.int64)
    g2 = df["g2"].to_numpy(dtype=np.float64)
    counts = df["H"].to_numpy(dtype=np.float64)
    total_state_mass = 0.0
    mean_acc = 0.0
    for state in np.unique(g1):
        idx = np.flatnonzero(g1 == state)
        state_mass = float(counts[idx].sum())
        if state_mass <= 0:
            continue
        lw = log_base[idx] + float(eta) * g2[idx]
        lz = logsumexp(lw)
        if not math.isfinite(lz):
            raise ValueError(f"No finite candidate mass for g1={int(state)}")
        probs = np.exp(lw - lz)
        mean_acc += state_mass * float(np.dot(probs, g2[idx]))
        total_state_mass += state_mass
    return mean_acc / total_state_mass if total_state_mass > 0 else math.nan


def solve_eta_conditional_strict(
    df: pd.DataFrame,
    log_base: np.ndarray,
    target_mean: float,
    *,
    tolerance: float = 1e-10,
    max_iter: int = 160,
) -> tuple[float, float]:
    """Solve the common terminal mean anchor, failing if it is unattainable."""
    log_base = np.asarray(log_base, dtype=np.float64)
    if len(log_base) != len(df):
        raise ValueError("log_base length does not match support")
    if not np.isfinite(log_base).all():
        raise ValueError("All eight vertices must be finite on the common support")

    g1 = df["g1"].to_numpy(dtype=np.int64)
    g2 = df["g2"].to_numpy(dtype=np.float64)
    counts = df["H"].to_numpy(dtype=np.float64)
    total = float(counts.sum())
    if total <= 0:
        raise ValueError("Cannot anchor a cell with non-positive empirical event mass")

    min_acc = 0.0
    max_acc = 0.0
    state_mass_total = 0.0
    for state in np.unique(g1):
        idx = np.flatnonzero(g1 == state)
        state_mass = float(counts[idx].sum())
        if state_mass <= 0:
            continue
        min_acc += state_mass * float(np.min(g2[idx]))
        max_acc += state_mass * float(np.max(g2[idx]))
        state_mass_total += state_mass
    lower_bound = min_acc / state_mass_total
    upper_bound = max_acc / state_mass_total
    if target_mean < lower_bound - tolerance or target_mean > upper_bound + tolerance:
        raise ValueError(
            "Terminal target is outside the common conditional-support range: "
            f"target={target_mean}, range=[{lower_bound},{upper_bound}]"
        )

    mean_zero = conditional_mean_at_eta(df, log_base, 0.0)
    if abs(mean_zero - target_mean) <= tolerance:
        return 0.0, float(mean_zero)

    lo, hi = -0.125, 0.125
    mlo = conditional_mean_at_eta(df, log_base, lo)
    mhi = conditional_mean_at_eta(df, log_base, hi)
    for _ in range(20):
        if mlo <= target_mean <= mhi:
            break
        if target_mean < mlo:
            hi, mhi = lo, mlo
            lo *= 2.0
            mlo = conditional_mean_at_eta(df, log_base, lo)
        else:
            lo, mlo = hi, mhi
            hi *= 2.0
            mhi = conditional_mean_at_eta(df, log_base, hi)
    else:
        raise ValueError(
            f"Could not bracket eta for target={target_mean}; mean(lo)={mlo}, mean(hi)={mhi}"
        )

    for _ in range(int(max_iter)):
        mid = 0.5 * (lo + hi)
        mm = conditional_mean_at_eta(df, log_base, mid)
        if abs(mm - target_mean) <= tolerance:
            return float(mid), float(mm)
        if mm < target_mean:
            lo = mid
        else:
            hi = mid
    eta = 0.5 * (lo + hi)
    mean = conditional_mean_at_eta(df, log_base, eta)
    if abs(mean - target_mean) > max(tolerance * 10.0, 1e-12):
        raise ValueError(
            f"Eta solver did not reach target: target={target_mean}, mean={mean}, eta={eta}"
        )
    return float(eta), float(mean)


def conditional_log_probabilities(
    df: pd.DataFrame,
    log_base: np.ndarray,
    eta: float,
) -> np.ndarray:
    g1 = df["g1"].to_numpy(dtype=np.int64)
    g2 = df["g2"].to_numpy(dtype=np.float64)
    logw = np.asarray(log_base, dtype=np.float64) + float(eta) * g2
    out = np.full(len(df), -math.inf, dtype=np.float64)
    for state in np.unique(g1):
        idx = np.flatnonzero(g1 == state)
        lz = logsumexp(logw[idx])
        if not math.isfinite(lz):
            raise ValueError(f"No finite normalized probability for g1={int(state)}")
        out[idx] = logw[idx] - lz
    return out


def evaluate_model(
    df: pd.DataFrame,
    spec: ModelSpec,
    *,
    anchor_tolerance: float,
    support_hash: str,
    block: int,
    filter_name: str,
) -> dict[str, Any]:
    log_base = (
        int(spec.H) * df["_log_H"].to_numpy(dtype=np.float64)
        + int(spec.R) * df["_log_R"].to_numpy(dtype=np.float64)
        + int(spec.P) * df["_log_P"].to_numpy(dtype=np.float64)
    )
    counts = df["H"].to_numpy(dtype=np.float64)
    obs_mask = counts > 0
    n_events = float(counts[obs_mask].sum())
    if n_events <= 0:
        raise ValueError(f"B{block:02d}/{filter_name} has no observed events")
    target_mean = float(
        np.dot(counts[obs_mask], df.loc[obs_mask, "g2"].to_numpy(dtype=np.float64)) / n_events
    )
    eta, mean_model = solve_eta_conditional_strict(
        df,
        log_base,
        target_mean,
        tolerance=float(anchor_tolerance),
    )
    logp = conditional_log_probabilities(df, log_base, eta)
    if not np.isfinite(logp[obs_mask]).all():
        raise ValueError(f"{spec.name} assigns zero probability to an observed support cell")
    loglik_sum = float(np.dot(counts[obs_mask], logp[obs_mask]))
    loglik_per_event = loglik_sum / n_events
    empirical_entropy = weighted_empirical_cond_entropy(df)
    cross_entropy = -loglik_per_event
    conditional_kl = cross_entropy - empirical_entropy
    anchor_error = abs(mean_model - target_mean)
    return {
        "block": f"B{int(block):02d}",
        "filter": filter_name,
        "stratum": FILTER_TO_STRATUM[filter_name],
        "model": spec.name,
        "H": int(spec.H),
        "R": int(spec.R),
        "P": int(spec.P),
        "formula": spec.formula,
        "support_semantics": "parent_wide_triple_admissible_conditional_by_g1",
        "support_sha256": support_hash,
        "support_rows": int(len(df)),
        "observed_rows": int(obs_mask.sum()),
        "g1_states": int(df.loc[obs_mask, "g1"].nunique()),
        "n_events": n_events,
        "eta": float(eta),
        "target_mean_g2": target_mean,
        "mean_g2_model": float(mean_model),
        "anchor_abs_error": float(anchor_error),
        "loglik_sum": loglik_sum,
        "loglik_per_event": float(loglik_per_event),
        "cross_entropy": float(cross_entropy),
        "empirical_cond_entropy": float(empirical_entropy),
        "conditional_kl": float(conditional_kl),
    }


# ---------------------------------------------------------------------------
# Block evaluation
# ---------------------------------------------------------------------------


def read_parent_wide_block(path: str | Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    required = {"g1", "g2", "H"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"{path} missing required columns {sorted(missing)}")
    out = df[["g1", "g2", "H"]].copy()
    out["g1"] = pd.to_numeric(out["g1"], errors="raise").astype(np.int64)
    out["g2"] = pd.to_numeric(out["g2"], errors="raise").astype(np.int64)
    out["H"] = pd.to_numeric(out["H"], errors="raise").astype(np.float64)
    if (out["H"] < 0).any():
        raise ValueError(f"{path} contains negative H counts")
    if out.duplicated(["g1", "g2"]).any():
        out = out.groupby(["g1", "g2"], as_index=False, sort=True).agg(H=("H", "sum"))
    out["max_g"] = np.maximum(out["g1"].to_numpy(), out["g2"].to_numpy())
    return out.sort_values(["g1", "g2"], kind="mergesort").reset_index(drop=True)


def prepare_block_factors(
    block_df: pd.DataFrame,
    primes: Sequence[int],
    path_cache: pd.DataFrame,
    *,
    block: int,
) -> tuple[pd.DataFrame, dict[str, Any]]:
    df = block_df.copy()
    _, _, log_r, adm3 = singular_logs_for_pairs(
        df["g1"].to_numpy(dtype=np.int64),
        df["g2"].to_numpy(dtype=np.int64),
        primes,
    )
    unique_g2 = np.array(sorted(df["g2"].astype(int).unique()), dtype=np.int64)
    log_h_unique, adm2 = singular_log_s2_gap(unique_g2, primes)
    h_map = {int(g): float(v) for g, v in zip(unique_g2, log_h_unique)}
    h_adm_map = {int(g): bool(v) for g, v in zip(unique_g2, adm2)}
    df["_log_R"] = log_r
    df["_adm3"] = adm3
    df["_log_H"] = df["g2"].map(h_map).astype(float)
    df["_adm2_g2"] = df["g2"].map(h_adm_map).astype(bool)
    df = df.merge(path_cache, on=["g1", "g2"], how="left", validate="many_to_one")

    observed_inadmissible = int(((df["H"] > 0) & (~df["_adm3"])).sum())
    if observed_inadmissible:
        bad = df.loc[(df["H"] > 0) & (~df["_adm3"]), ["g1", "g2", "H"]].head()
        raise ValueError(
            f"B{int(block):02d} contains {observed_inadmissible} observed triple-inadmissible rows: "
            f"{bad.to_dict('records')}"
        )

    admissible_missing_path = int((df["_adm3"] & df["_log_P"].isna()).sum())
    if admissible_missing_path:
        bad = df.loc[df["_adm3"] & df["_log_P"].isna(), ["g1", "g2"]].head()
        raise ValueError(
            f"B{int(block):02d} has {admissible_missing_path} admissible rows missing from path cache: "
            f"{bad.to_dict('records')}"
        )

    common = (
        df["_adm3"].to_numpy(dtype=bool)
        & df["_adm2_g2"].to_numpy(dtype=bool)
        & np.isfinite(df["_log_R"].to_numpy(dtype=float))
        & np.isfinite(df["_log_H"].to_numpy(dtype=float))
        & np.isfinite(df["_log_P"].to_numpy(dtype=float))
    )
    outside_observed = int(((df["H"] > 0).to_numpy(dtype=bool) & (~common)).sum())
    if outside_observed:
        bad = df.loc[(df["H"] > 0).to_numpy(dtype=bool) & (~common), ["g1", "g2", "H"]].head()
        raise ValueError(
            f"B{int(block):02d} has {outside_observed} observed rows outside the common H/R/P support: "
            f"{bad.to_dict('records')}"
        )
    df = df.loc[common].reset_index(drop=True)
    meta = {
        "raw_support_rows": int(len(block_df)),
        "common_support_rows": int(len(df)),
        "triple_inadmissible_rows_dropped": int(len(block_df) - int(np.sum(adm3))),
        "observed_inadmissible_rows": observed_inadmissible,
        "admissible_path_cache_missing_rows": admissible_missing_path,
    }
    return df, meta


def evaluate_block(
    *,
    block: int,
    block_path: str | Path,
    path_cache_path: str | Path,
    primes: Sequence[int],
    filters: Sequence[str],
    anchor_tolerance: float,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    block_df = read_parent_wide_block(block_path)
    path_cache = load_path_cache(path_cache_path)
    prepared, block_meta = prepare_block_factors(block_df, primes, path_cache, block=block)

    metrics: list[dict[str, Any]] = []
    support_rows: list[dict[str, Any]] = []
    for filter_name in filters:
        mask = FILTERS[filter_name](prepared["max_g"].to_numpy(dtype=np.int64))
        cell = prepared.loc[mask].copy().reset_index(drop=True)
        if cell.empty or float(cell["H"].sum()) <= 0:
            continue
        observed_states = sorted(cell.loc[cell["H"] > 0, "g1"].astype(int).unique())
        if not observed_states:
            continue
        candidates_per_state = cell.groupby("g1").size()
        missing_observed_states = [state for state in observed_states if int(state) not in candidates_per_state.index]
        if missing_observed_states:  # pragma: no cover - defensive
            raise ValueError(
                f"B{block:02d}/{filter_name} missing conditional support for observed g1 states "
                f"{missing_observed_states[:8]}"
            )
        s_hash = support_sha256(cell)
        model_rows = [
            evaluate_model(
                cell,
                spec,
                anchor_tolerance=anchor_tolerance,
                support_hash=s_hash,
                block=block,
                filter_name=filter_name,
            )
            for spec in MODEL_SPECS
        ]
        metrics.extend(model_rows)
        target_values = {round(float(row["target_mean_g2"]), 12) for row in model_rows}
        support_hashes = {str(row["support_sha256"]) for row in model_rows}
        anchor_max = max(float(row["anchor_abs_error"]) for row in model_rows)
        support_rows.append(
            {
                "block": f"B{int(block):02d}",
                "filter": filter_name,
                "stratum": FILTER_TO_STRATUM[filter_name],
                "support_semantics": "parent_wide_triple_admissible_conditional_by_g1",
                "support_sha256": s_hash,
                "support_rows": int(len(cell)),
                "observed_rows": int((cell["H"] > 0).sum()),
                "g1_states_observed": int(len(observed_states)),
                "min_candidates_per_g1": int(candidates_per_state.loc[observed_states].min()),
                "max_candidates_per_g1": int(candidates_per_state.loc[observed_states].max()),
                "n_events": float(cell["H"].sum()),
                "target_mean_g2": float(model_rows[0]["target_mean_g2"]),
                "model_vertices": int(len(model_rows)),
                "unique_support_hashes_across_vertices": int(len(support_hashes)),
                "unique_targets_across_vertices": int(len(target_values)),
                "anchor_max_abs_error": float(anchor_max),
                "common_support_gate_pass": bool(
                    len(model_rows) == 8 and len(support_hashes) == 1 and len(target_values) == 1
                ),
                "anchor_gate_pass": bool(anchor_max <= float(anchor_tolerance) * 10.0),
            }
        )
    return metrics, support_rows, block_meta


def _evaluate_block_task(task: tuple[Any, ...]):
    block, block_path, cache_path, primes, filters, anchor_tolerance = task
    return evaluate_block(
        block=int(block),
        block_path=block_path,
        path_cache_path=cache_path,
        primes=tuple(int(p) for p in primes),
        filters=tuple(str(x) for x in filters),
        anchor_tolerance=float(anchor_tolerance),
    )


# ---------------------------------------------------------------------------
# Summaries, factorial effects, and context effects
# ---------------------------------------------------------------------------


def summarize_models(metrics: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for (filter_name, stratum, model), sub in metrics.groupby(
        ["filter", "stratum", "model"], sort=True
    ):
        total_events = float(sub["n_events"].sum())
        loglik_sum = float(sub["loglik_sum"].sum())
        ll = loglik_sum / total_events
        h_emp = float(np.average(sub["empirical_cond_entropy"], weights=sub["n_events"]))
        cross_entropy = -ll
        spec = MODEL_BY_NAME[str(model)]
        rows.append(
            {
                "filter": filter_name,
                "stratum": stratum,
                "model": model,
                "H": spec.H,
                "R": spec.R,
                "P": spec.P,
                "n_blocks": int(sub["block"].nunique()),
                "n_events": total_events,
                "loglik_sum": loglik_sum,
                "loglik_per_event": ll,
                "cross_entropy": cross_entropy,
                "empirical_cond_entropy": h_emp,
                "conditional_kl": cross_entropy - h_emp,
                "eta_mean": float(sub["eta"].mean()),
                "eta_std": float(sub["eta"].std(ddof=1)) if len(sub) > 1 else 0.0,
                "eta_min": float(sub["eta"].min()),
                "eta_max": float(sub["eta"].max()),
                "anchor_max_abs_error": float(sub["anchor_abs_error"].max()),
            }
        )
    out = pd.DataFrame(rows)
    if not out.empty:
        out["rank_by_loglik"] = (
            out.groupby("filter")["loglik_per_event"]
            .rank(method="min", ascending=False)
            .astype(int)
        )
    return out.sort_values(["filter", "rank_by_loglik", "model"], kind="mergesort").reset_index(drop=True)


def factorial_effects_from_values(values: Mapping[tuple[int, int, int], float]) -> dict[str, float]:
    missing = sorted(set(MODEL_BY_SIGNATURE) - set(values))
    if missing:
        raise ValueError(f"Incomplete factorial cube; missing signatures {missing}")
    result: dict[str, float] = {}
    index = {"H": 0, "R": 1, "P": 2}
    for effect_name, factors in FACTORIAL_EFFECTS:
        contrast = 0.0
        for signature, response in values.items():
            sign = 1.0
            for factor in factors:
                level = signature[index[factor]]
                sign *= 1.0 if int(level) == 1 else -1.0
            contrast += sign * float(response)
        result[effect_name] = float(contrast / 4.0)
    return result


def build_missing_cells(
    metrics: pd.DataFrame,
    *,
    expected_blocks: Sequence[str] | None = None,
    expected_filters: Sequence[str] | None = None,
) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    blocks = list(expected_blocks or sorted(metrics.get("block", pd.Series(dtype=str)).astype(str).unique()))
    filters = list(expected_filters or sorted(metrics.get("filter", pd.Series(dtype=str)).astype(str).unique()))
    for block in blocks:
        for filter_name in filters:
            stratum = FILTER_TO_STRATUM[str(filter_name)]
            sub = metrics[
                (metrics["block"].astype(str) == str(block))
                & (metrics["filter"].astype(str) == str(filter_name))
            ] if not metrics.empty else metrics
            counts = sub["model"].value_counts() if not sub.empty else pd.Series(dtype=int)
            for model in MODEL_BY_NAME:
                count = int(counts.get(model, 0))
                if count == 0:
                    rows.append(
                        {
                            "block": str(block),
                            "filter": str(filter_name),
                            "stratum": stratum,
                            "model": model,
                            "reason": "missing_block_filter_cell" if sub.empty else "missing_vertex",
                        }
                    )
                elif count > 1:
                    rows.append(
                        {
                            "block": str(block),
                            "filter": str(filter_name),
                            "stratum": stratum,
                            "model": model,
                            "reason": f"duplicate_vertex_count_{count}",
                        }
                    )
    return pd.DataFrame(rows, columns=MISSING_CELL_COLUMNS)


def build_factorial_effects_by_block(metrics: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for (block, filter_name, stratum), sub in metrics.groupby(
        ["block", "filter", "stratum"], sort=True
    ):
        values = {
            MODEL_BY_NAME[str(row.model)].signature: float(row.loglik_per_event)
            for row in sub.itertuples(index=False)
        }
        effects = factorial_effects_from_values(values)
        n_events_values = sub["n_events"].astype(float).unique()
        if len(n_events_values) != 1:
            raise ValueError(f"Inconsistent event totals across vertices in {block}/{filter_name}")
        for effect_name, value in effects.items():
            rows.append(
                {
                    "block": block,
                    "filter": filter_name,
                    "stratum": stratum,
                    "effect": effect_name,
                    "effect_loglik_per_event": float(value),
                    "n_events": float(n_events_values[0]),
                    "contrast_divisor": 4,
                }
            )
    return pd.DataFrame(rows)


def _pooled_factorial_effects(model_summary: pd.DataFrame) -> dict[tuple[str, str], float]:
    pooled: dict[tuple[str, str], float] = {}
    for (filter_name, _stratum), sub in model_summary.groupby(["filter", "stratum"], sort=True):
        values = {
            MODEL_BY_NAME[str(row.model)].signature: float(row.loglik_per_event)
            for row in sub.itertuples(index=False)
        }
        for effect_name, value in factorial_effects_from_values(values).items():
            pooled[(str(filter_name), effect_name)] = float(value)
    return pooled


def summarize_factorial_effects(
    effects_by_block: pd.DataFrame,
    model_summary: pd.DataFrame,
) -> pd.DataFrame:
    pooled = _pooled_factorial_effects(model_summary)
    rows: list[dict[str, Any]] = []
    for (filter_name, stratum, effect), sub in effects_by_block.groupby(
        ["filter", "stratum", "effect"], sort=True
    ):
        values = sub["effect_loglik_per_event"].astype(float)
        positive = int((values > 0).sum())
        negative = int((values < 0).sum())
        rows.append(
            {
                "filter": filter_name,
                "stratum": stratum,
                "effect": effect,
                "pooled_effect_loglik_per_event": pooled[(str(filter_name), str(effect))],
                "n_blocks": int(len(values)),
                "mean_by_block": float(values.mean()),
                "std_by_block": float(values.std(ddof=1)) if len(values) > 1 else 0.0,
                "min_by_block": float(values.min()),
                "max_by_block": float(values.max()),
                "positive_blocks": positive,
                "negative_blocks": negative,
                "zero_blocks": int(len(values) - positive - negative),
                "all_blocks_same_nonzero_sign": bool(positive == len(values) or negative == len(values)),
            }
        )
    return pd.DataFrame(rows)


def context_effect_definitions() -> list[dict[str, Any]]:
    definitions: list[dict[str, Any]] = []
    factor_index = {"H": 0, "R": 1, "P": 2}
    for factor in FACTOR_NAMES:
        idx = factor_index[factor]
        other = [x for x in FACTOR_NAMES if x != factor]
        for level_a in (0, 1):
            for level_b in (0, 1):
                low = [0, 0, 0]
                high = [0, 0, 0]
                low[idx] = 0
                high[idx] = 1
                low[factor_index[other[0]]] = high[factor_index[other[0]]] = level_a
                low[factor_index[other[1]]] = high[factor_index[other[1]]] = level_b
                low_sig = tuple(low)
                high_sig = tuple(high)
                definitions.append(
                    {
                        "factor": factor,
                        "context": f"{other[0]}={level_a};{other[1]}={level_b}",
                        "other_factor_1": other[0],
                        "other_level_1": level_a,
                        "other_factor_2": other[1],
                        "other_level_2": level_b,
                        "low_signature": low_sig,
                        "high_signature": high_sig,
                        "model_low": MODEL_BY_SIGNATURE[low_sig].name,
                        "model_high": MODEL_BY_SIGNATURE[high_sig].name,
                    }
                )
    return definitions


CONTEXT_EFFECTS = context_effect_definitions()


def build_context_effects_by_block(metrics: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for (block, filter_name, stratum), sub in metrics.groupby(
        ["block", "filter", "stratum"], sort=True
    ):
        values = {str(row.model): float(row.loglik_per_event) for row in sub.itertuples(index=False)}
        n_events_values = sub["n_events"].astype(float).unique()
        if len(n_events_values) != 1:
            raise ValueError(f"Inconsistent event totals across vertices in {block}/{filter_name}")
        for definition in CONTEXT_EFFECTS:
            low = definition["model_low"]
            high = definition["model_high"]
            rows.append(
                {
                    "block": block,
                    "filter": filter_name,
                    "stratum": stratum,
                    "factor": definition["factor"],
                    "context": definition["context"],
                    "model_low": low,
                    "model_high": high,
                    "delta_loglik_per_event": float(values[high] - values[low]),
                    "n_events": float(n_events_values[0]),
                }
            )
    return pd.DataFrame(rows)


def summarize_context_effects(
    context_by_block: pd.DataFrame,
    model_summary: pd.DataFrame,
) -> pd.DataFrame:
    pooled_model_values = {
        (str(row.filter), str(row.model)): float(row.loglik_per_event)
        for row in model_summary.itertuples(index=False)
    }
    rows: list[dict[str, Any]] = []
    for (filter_name, stratum, factor, context, model_low, model_high), sub in context_by_block.groupby(
        ["filter", "stratum", "factor", "context", "model_low", "model_high"], sort=True
    ):
        values = sub["delta_loglik_per_event"].astype(float)
        pooled_delta = pooled_model_values[(str(filter_name), str(model_high))] - pooled_model_values[
            (str(filter_name), str(model_low))
        ]
        positive = int((values > 0).sum())
        negative = int((values < 0).sum())
        rows.append(
            {
                "filter": filter_name,
                "stratum": stratum,
                "factor": factor,
                "context": context,
                "model_low": model_low,
                "model_high": model_high,
                "pooled_delta_loglik_per_event": float(pooled_delta),
                "n_blocks": int(len(values)),
                "mean_by_block": float(values.mean()),
                "std_by_block": float(values.std(ddof=1)) if len(values) > 1 else 0.0,
                "min_by_block": float(values.min()),
                "max_by_block": float(values.max()),
                "positive_blocks": positive,
                "negative_blocks": negative,
                "zero_blocks": int(len(values) - positive - negative),
                "all_blocks_same_nonzero_sign": bool(positive == len(values) or negative == len(values)),
            }
        )
    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# Interpretation and gates
# ---------------------------------------------------------------------------


def _effect_label(value: float, tolerance: float = 1e-12) -> str:
    if value > tolerance:
        return "positive/synergistic"
    if value < -tolerance:
        return "negative/antagonistic"
    return "near-zero"


def build_gate_summary(
    *,
    metrics: pd.DataFrame,
    support_audit: pd.DataFrame,
    missing_cells: pd.DataFrame,
    effects_by_block: pd.DataFrame,
    context_by_block: pd.DataFrame,
    anchor_tolerance: float,
    expected_cells: int | None = None,
) -> dict[str, Any]:
    actual_cells = int(support_audit.shape[0])
    cells = int(actual_cells if expected_cells is None else expected_cells)
    expected_metric_rows = cells * 8
    expected_effect_rows = cells * 7
    expected_context_rows = cells * 12
    complete = bool(
        missing_cells.empty
        and actual_cells == cells
        and len(metrics) == expected_metric_rows
    )
    common_support = bool(
        not support_audit.empty
        and support_audit["common_support_gate_pass"].astype(bool).all()
    )
    anchor_max = float(metrics["anchor_abs_error"].max()) if not metrics.empty else math.inf
    anchor_pass = bool(anchor_max <= float(anchor_tolerance) * 10.0)
    effects_complete = bool(len(effects_by_block) == expected_effect_rows)
    contexts_complete = bool(len(context_by_block) == expected_context_rows)
    finite_metrics = bool(
        not metrics.empty
        and np.isfinite(
            metrics[
                [
                    "loglik_sum",
                    "loglik_per_event",
                    "conditional_kl",
                    "eta",
                    "mean_g2_model",
                ]
            ].to_numpy(dtype=float)
        ).all()
    )
    gate_pass = bool(
        complete
        and common_support
        and anchor_pass
        and effects_complete
        and contexts_complete
        and finite_metrics
    )
    return {
        "expected_block_filter_cells": cells,
        "actual_block_filter_cells": actual_cells,
        "expected_model_metric_rows": expected_metric_rows,
        "actual_model_metric_rows": int(len(metrics)),
        "expected_factorial_effect_rows": expected_effect_rows,
        "actual_factorial_effect_rows": int(len(effects_by_block)),
        "expected_context_effect_rows": expected_context_rows,
        "actual_context_effect_rows": int(len(context_by_block)),
        "missing_cell_rows": int(len(missing_cells)),
        "complete_factorial_cube_gate_pass": complete,
        "common_support_gate_pass": common_support,
        "anchor_max_abs_error": anchor_max,
        "anchor_tolerance": float(anchor_tolerance),
        "terminal_anchor_gate_pass": anchor_pass,
        "factorial_effects_complete_gate_pass": effects_complete,
        "context_effects_complete_gate_pass": contexts_complete,
        "finite_metrics_gate_pass": finite_metrics,
        "a10_release_gate_pass": gate_pass,
    }


def write_interpretation(
    output_dir: Path,
    model_summary: pd.DataFrame,
    factorial_summary: pd.DataFrame,
    context_summary: pd.DataFrame,
    gates: Mapping[str, Any],
) -> dict[str, Any]:
    lines: list[str] = []
    lines.append("# CHL2 H/R/P factor-compatibility audit")
    lines.append("")
    lines.append(
        "This public audit evaluates the complete conditional $2^3$ design for the marginal pair factor $H$, the conditional ratio $R$, and path survival $P$. All eight vertices use the same triple-admissible conditional support and the same terminal mean-$g_2$ target."
    )
    lines.append("")
    lines.append("## Release gate")
    lines.append("")
    lines.append(f"- Complete eight-vertex cube: `{bool(gates['complete_factorial_cube_gate_pass'])}`.")
    lines.append(f"- Common support across vertices: `{bool(gates['common_support_gate_pass'])}`.")
    lines.append(f"- Terminal-anchor tolerance: `{bool(gates['terminal_anchor_gate_pass'])}`.")
    lines.append(f"- A10 release gate: `{bool(gates['a10_release_gate_pass'])}`.")
    lines.append("")

    all_models = model_summary[model_summary["filter"].astype(str) == "ALL"].copy()
    all_effects = factorial_summary[factorial_summary["filter"].astype(str) == "ALL"].copy()
    all_context = context_summary[context_summary["filter"].astype(str) == "ALL"].copy()

    outcome: dict[str, Any] = {
        "a10_release_gate_pass": bool(gates["a10_release_gate_pass"]),
        "best_model_all": None,
        "factorial_effects_all": {},
    }
    if not all_models.empty:
        table = all_models.sort_values("loglik_per_event", ascending=False)[
            [
                "rank_by_loglik",
                "model",
                "H",
                "R",
                "P",
                "loglik_per_event",
                "conditional_kl",
                "n_blocks",
            ]
        ]
        best = str(table.iloc[0]["model"])
        outcome["best_model_all"] = best
        lines.append("## Model ranking, $S_{all}$")
        lines.append("")
        lines.append(safe_to_markdown(table, index=False))
        lines.append("")
        lines.append(f"The highest pooled conditional log-likelihood among the eight vertices is produced by `{best}`.")
        lines.append("")

    if not all_effects.empty:
        table = all_effects[
            [
                "effect",
                "pooled_effect_loglik_per_event",
                "mean_by_block",
                "min_by_block",
                "max_by_block",
                "positive_blocks",
                "negative_blocks",
            ]
        ]
        lines.append("## Factorial effects, $S_{all}$")
        lines.append("")
        lines.append(safe_to_markdown(table, index=False))
        lines.append("")
        effects_map = {
            str(row.effect): float(row.pooled_effect_loglik_per_event)
            for row in all_effects.itertuples(index=False)
        }
        outcome["factorial_effects_all"] = effects_map
        for interaction in ("H:R", "H:P", "R:P", "H:R:P"):
            if interaction in effects_map:
                value = effects_map[interaction]
                lines.append(
                    f"- `{interaction}` is {_effect_label(value)} on the pooled log-likelihood scale (`{value:.8g}` nats/event)."
                )
        lines.append("")

    if not all_context.empty:
        table = all_context[
            [
                "factor",
                "context",
                "model_low",
                "model_high",
                "pooled_delta_loglik_per_event",
                "positive_blocks",
                "negative_blocks",
            ]
        ]
        lines.append("## Context-dependent additions, $S_{all}$")
        lines.append("")
        lines.append(safe_to_markdown(table, index=False))
        lines.append("")
        lines.append(
            "A positive row means that adding the named factor improves conditional log-likelihood while the other two factors are held fixed. A negative row means that the same factor is detrimental in that multiplicative context."
        )
        lines.append("")

    lines.append("## Reading rule")
    lines.append("")
    lines.append(
        "The effects are empirical compatibility contrasts, not mechanistic theorems. A negative interaction means that the joint gain is smaller than additive on the conditional log-likelihood scale; it does not by itself prove formal double counting. Likewise, a factor that helps in one context need not improve every kernel that contains it."
    )
    lines.append("")
    lines.append(
        "The production CHL2 kernel remains the $R\times P$ vertex. The marginal pair factor $H$ is evaluated here as an ablation coordinate and should not be multiplied into a production candidate solely because its isolated main effect is positive."
    )
    lines.append("")

    (output_dir / "chl2_factor_compatibility_interpretation.md").write_text(
        "\n".join(lines), encoding="utf-8"
    )
    return outcome


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True, help="DS1 generated config JSON")
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument("--blocks", default=None, help="Block spec, for example 1-10")
    parser.add_argument("--filters", default=",".join(FILTERS), help="Comma-separated public filter names")
    parser.add_argument("--Y", type=int, default=None, help="Singular-series truncation; default config pmax")
    parser.add_argument("--log-x", type=float, default=None, help="Local log(x); default log(config start_x)")
    parser.add_argument("--path-cache-file", required=True, help="A02 path-exclusion cache CSV/CSV.GZ")
    parser.add_argument("--workers", type=int, default=1, help="Block workers; 0 means all detected CPUs")
    parser.add_argument("--anchor-tolerance", type=float, default=1e-10)
    parser.add_argument("--hash-inputs", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)

    telemetry = telemetry_start()
    config_path = Path(args.config)
    root = Path(args.root)
    output_dir = Path(args.output_dir)
    config = load_json(config_path)
    blocks = parse_block_spec(args.blocks, config.get("blocks", list(range(1, 11))))
    filters = parse_csv_list(args.filters)
    unknown = sorted(set(filters) - set(FILTERS))
    if unknown:
        raise ValueError(f"Unknown filters {unknown}; available={sorted(FILTERS)}")
    block_files = resolve_block_files(config, root, blocks)
    Y = int(args.Y if args.Y is not None else config.get("pmax", 47))
    if Y < 2:
        raise ValueError("Y must be >= 2")
    primes = primes_upto(Y)
    start_x = float(config.get("start_x", 1e11))
    log_x = float(args.log_x if args.log_x is not None else math.log(start_x))
    path_cache_path = Path(args.path_cache_file)
    if not path_cache_path.is_file():
        raise FileNotFoundError(path_cache_path)
    workers = (os.cpu_count() or 1) if int(args.workers) == 0 else max(1, int(args.workers))

    input_paths: dict[str, str | Path | None] = {
        "config": config_path,
        "path_cache": path_cache_path,
    }
    for block, path in block_files:
        input_paths[f"parent_wide_B{block:02d}"] = path
    provenance = build_provenance(
        repo_root=root,
        input_paths=input_paths,
        hash_inputs=bool(args.hash_inputs),
    )

    run_config: dict[str, Any] = {
        "phase": "A10_CHL2_FACTOR_COMPATIBILITY",
        "config": str(config_path),
        "root": str(root),
        "blocks": blocks,
        "block_files": [str(path) for _, path in block_files],
        "filters": filters,
        "filter_to_stratum": {name: FILTER_TO_STRATUM[name] for name in filters},
        "Y": Y,
        "truncation_primes": primes,
        "log_x": log_x,
        "path_cache_file": str(path_cache_path),
        "workers_requested": int(args.workers),
        "workers_effective": workers,
        "anchor_tolerance": float(args.anchor_tolerance),
        "support_semantics": "parent_wide_triple_admissible_conditional_by_g1",
        "anchor_semantics": "model_specific_eta_common_empirical_mean_g2_by_block_filter",
        "factor_definitions": {
            "H": "S_Y({0,g2})",
            "R": "S_Y({0,g1,g1+g2})/S_Y({0,g1})",
            "P": "exp[-Omega_Y^path(g1,g2;x)]",
        },
        "models": [asdict(spec) for spec in MODEL_SPECS],
        "provenance": provenance,
    }
    if args.dry_run:
        print(json.dumps(run_config, indent=2, sort_keys=True))
        return 0

    output_dir.mkdir(parents=True, exist_ok=True)
    tasks = [
        (
            block,
            str(path),
            str(path_cache_path),
            tuple(primes),
            tuple(filters),
            float(args.anchor_tolerance),
        )
        for block, path in block_files
    ]
    all_metrics: list[dict[str, Any]] = []
    all_support: list[dict[str, Any]] = []
    block_meta: dict[str, Any] = {}
    if workers > 1 and len(tasks) > 1:
        with ProcessPoolExecutor(max_workers=min(workers, len(tasks))) as executor:
            futures = {executor.submit(_evaluate_block_task, task): int(task[0]) for task in tasks}
            for future in as_completed(futures):
                block = futures[future]
                metrics_rows, support_rows, meta = future.result()
                all_metrics.extend(metrics_rows)
                all_support.extend(support_rows)
                block_meta[f"B{block:02d}"] = meta
                print(f"[A10] completed B{block:02d}", flush=True)
    else:
        for task in tasks:
            block = int(task[0])
            metrics_rows, support_rows, meta = _evaluate_block_task(task)
            all_metrics.extend(metrics_rows)
            all_support.extend(support_rows)
            block_meta[f"B{block:02d}"] = meta
            print(f"[A10] completed B{block:02d}", flush=True)

    metrics = pd.DataFrame(all_metrics, columns=MODEL_METRIC_COLUMNS)
    if metrics.empty:
        raise ValueError("A10 produced no model metrics")
    metrics = metrics.sort_values(["block", "filter", "H", "R", "P"], kind="mergesort").reset_index(drop=True)
    metrics["rank_within_block_filter"] = (
        metrics.groupby(["block", "filter"])["loglik_per_event"]
        .rank(method="min", ascending=False)
        .astype(int)
    )
    support_audit = pd.DataFrame(all_support).sort_values(["block", "filter"], kind="mergesort").reset_index(drop=True)
    expected_block_labels = [f"B{int(block):02d}" for block in blocks]
    missing_cells = build_missing_cells(
        metrics,
        expected_blocks=expected_block_labels,
        expected_filters=filters,
    )
    model_summary = summarize_models(metrics)
    factorial_by_block = build_factorial_effects_by_block(metrics)
    factorial_summary = summarize_factorial_effects(factorial_by_block, model_summary)
    context_by_block = build_context_effects_by_block(metrics)
    context_summary = summarize_context_effects(context_by_block, model_summary)
    gates = build_gate_summary(
        metrics=metrics,
        support_audit=support_audit,
        missing_cells=missing_cells,
        effects_by_block=factorial_by_block,
        context_by_block=context_by_block,
        anchor_tolerance=float(args.anchor_tolerance),
        expected_cells=len(blocks) * len(filters),
    )
    interpretation_summary = write_interpretation(
        output_dir,
        model_summary,
        factorial_summary,
        context_summary,
        gates,
    )

    outputs = {
        "chl2_factor_model_metrics_by_block.csv": metrics,
        "chl2_factor_model_summary.csv": model_summary,
        "chl2_factorial_effects_by_block.csv": factorial_by_block,
        "chl2_factorial_effects_summary.csv": factorial_summary,
        "chl2_factor_context_effects_by_block.csv": context_by_block,
        "chl2_factor_context_effects_summary.csv": context_summary,
        "chl2_factor_missing_cells.csv": missing_cells,
        "chl2_factor_support_audit.csv": support_audit,
    }
    for name, frame in outputs.items():
        frame.to_csv(output_dir / name, index=False)

    output_files = list(outputs) + [
        "chl2_factor_compatibility_interpretation.md",
        "chl2_factor_compatibility_config.json",
        "chl2_factor_compatibility_telemetry.json",
    ]
    run_config.update(
        {
            "output_dir": str(output_dir),
            "output_files": output_files,
            "block_preparation": block_meta,
            "gates": gates,
            "interpretation_summary": interpretation_summary,
        }
    )
    (output_dir / "chl2_factor_compatibility_config.json").write_text(
        json.dumps(run_config, indent=2, sort_keys=True), encoding="utf-8"
    )
    write_telemetry(
        output_dir / "chl2_factor_compatibility_telemetry.json",
        telemetry,
        **run_config,
        model_metric_rows=int(len(metrics)),
        model_summary_rows=int(len(model_summary)),
        factorial_effect_rows=int(len(factorial_by_block)),
        factorial_summary_rows=int(len(factorial_summary)),
        context_effect_rows=int(len(context_by_block)),
        context_summary_rows=int(len(context_summary)),
        support_audit_rows=int(len(support_audit)),
        missing_cell_rows=int(len(missing_cells)),
    )
    print(f"[A10] release gate: {gates['a10_release_gate_pass']}")
    print(f"[A10] wrote outputs to {output_dir}")
    return 0 if gates["a10_release_gate_pass"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
