#!/usr/bin/env python3
"""Validate that a CHL3 audit output directory was generated by the expected
multimodel + self/cluster + vectorized-OS pipeline.

This script is intentionally lightweight: it only reads the CSV/JSON outputs and
checks structural consistency before launching expensive B01--B10 runs.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

EXPECTED_CORE_MODELS = {
    "CHL2_path_excl_cond_eta",
    "CHL2_bernoulli_path_cond_eta",
    "CHL3_lowwheel2_p3_cond_eta",
    "CHL3_lowwheel2_p3p5_cond_eta",
    "CHL3_lowwheel2_p3p5p7_cond_eta",
    "CHL3_self_lowwheel2_p3_cond_eta",
    "CHL3_self_lowwheel2_p3p5_cond_eta",
    "CHL3_self_lowwheel2_p3p5p7_cond_eta",
}

REQUIRED_FILES = [
    "chl3_config.json",
    "chl3_cluster_telemetry.json",
    "chl3_conditional_summary.csv",
    "chl3_os_prime_residue_status.json",
    "chl3_os_prime_residue_summary.csv",
    "chl3_os_prime_residue_transition_by_mod.csv",
    "chl3_q3_diagnostic.csv",
]


def fail(msg: str) -> None:
    raise SystemExit(f"[FAIL] {msg}")


def warn(msg: str) -> None:
    print(f"[WARN] {msg}")


def ok(msg: str) -> None:
    print(f"[OK] {msg}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("output_dir", type=Path)
    ap.add_argument("--expect-multimodel", action="store_true", default=True)
    ap.add_argument("--tolerance", type=float, default=1e-6)
    args = ap.parse_args()

    out = args.output_dir
    if not out.exists():
        fail(f"output_dir does not exist: {out}")

    for name in REQUIRED_FILES:
        if not (out / name).exists():
            fail(f"missing required file: {name}")
    ok("required files present")

    cfg = json.loads((out / "chl3_config.json").read_text(encoding="utf-8"))
    tel = json.loads((out / "chl3_cluster_telemetry.json").read_text(encoding="utf-8"))
    status = json.loads((out / "chl3_os_prime_residue_status.json").read_text(encoding="utf-8"))

    models_cfg = set(cfg.get("models", []))
    missing_models = EXPECTED_CORE_MODELS - models_cfg
    if missing_models:
        fail("config does not include expected CHL3 self/multimodel models: " + ", ".join(sorted(missing_models)))
    ok("config includes CHL2, CHL3 lowwheel, and CHL3 self+cluster models")

    if not status.get("ran"):
        fail(f"OS diagnostic did not run: {status}")
    ok("OS diagnostic status says ran=true")

    cs = pd.read_csv(out / "chl3_conditional_summary.csv")
    models_summary = set(cs["model"].unique())
    missing_summary = EXPECTED_CORE_MODELS - models_summary
    if missing_summary:
        fail("conditional_summary missing expected models: " + ", ".join(sorted(missing_summary)))
    ok("conditional_summary contains all expected experimental models")

    os_sum = pd.read_csv(out / "chl3_os_prime_residue_summary.csv")
    if set(os_sum["q"].unique()) != {3, 5, 7}:
        fail(f"OS summary q values are {sorted(os_sum['q'].unique())}, expected [3,5,7]")
    ok("OS summary contains q=3,5,7")

    if args.expect_multimodel:
        missing_os_models = EXPECTED_CORE_MODELS - set(os_sum["model"].unique())
        if missing_os_models:
            fail("OS summary is not multimodel; missing: " + ", ".join(sorted(missing_os_models)))
        expected_min_rows = 3 * len(EXPECTED_CORE_MODELS)
        if len(os_sum) < expected_min_rows:
            fail(f"OS summary has {len(os_sum)} rows, expected at least {expected_min_rows}")
        ok("OS summary is multimodel")

    trans = pd.read_csv(out / "chl3_os_prime_residue_transition_by_mod.csv")
    needed_cols = {"row_count", "model_probability", "expected_count_model"}
    if not needed_cols.issubset(trans.columns):
        fail("OS transition CSV missing one of: row_count, model_probability, expected_count_model")
    diff = (trans["expected_count_model"] - trans["row_count"] * trans["model_probability"]).abs().max()
    if diff > args.tolerance:
        fail(f"expected_count_model inconsistent; max abs diff = {diff}")
    ok("expected_count_model equals row_count * model_probability")

    # Find cache from config/telemetry and test hard-zero columns.
    cache_path = None
    for key in ["cluster_cache_file", "unique_pair_cache_file"]:
        val = cfg.get(key) or tel.get(key)
        if val:
            p = Path(val)
            if not p.is_absolute():
                p = out.parent / p if not (out / p.name).exists() else out / p.name
            if p.exists():
                cache_path = p
                break
            if (out / Path(val).name).exists():
                cache_path = out / Path(val).name
                break
    if cache_path is None:
        # fallback: first matching cache in output dir
        matches = list(out.glob("chl3_cluster_cache_*.csv.gz"))
        if matches:
            cache_path = matches[0]
    if cache_path is None or not cache_path.exists():
        warn("could not locate cluster cache; hard-zero/self columns not checked")
    else:
        cache = pd.read_csv(cache_path, nrows=5)
        required_cache_cols = {
            "hard_zero_h5_pairs_p3",
            "hard_zero_h5_weight_p3",
            "hard_zero_h5_kappa_mass_p3",
            "omega_self_lowwheel2_p3",
            "omega_self_lowwheel2_p3p5",
            "omega_self_lowwheel2_p3p5p7",
        }
        missing_cache = required_cache_cols - set(cache.columns)
        if missing_cache:
            fail("cluster cache missing hard-zero/self columns: " + ", ".join(sorted(missing_cache)))
        ok("cluster cache has hard-zero and self+cluster telemetry columns")

    q3 = os_sum[os_sum["q"] == 3]
    if not q3.empty:
        print("\nq=3 summary by model:")
        cols = ["model", "diagonal_probability_empirical", "diagonal_probability_model", "diagonal_wrong_sign_vs_uniform", "pearson_chi2_per_transition"]
        print(q3[cols].to_string(index=False))

    print("\n[PASS] CHL3 output integrity checks passed.")


if __name__ == "__main__":
    main()
